
data:
  nodes:
    path: data/all_nodes_withtier.csv
    id_col: location_id
    lat_col: lat
    lon_col: long
    location_name_col: location_name
    province_col: province
    tier_col: tier
    population_col: population_2024
    type_col: location_type

    attribute_groups:
      - name: "Points of Interests"
        columns: ['count_711', 'mercury_count', 'watsons_total_count']
      - name: "Amenities"
        columns: ['amenity_count','amenity_density_scaled','amenity_proximity_scaled','amenity_entropy_scaled','amenity_equity_scaled', 'shop','restaurant','school','bank','fast_food','place_of_worship','fuel','pharmacy','cafe','parking','townhall','bar','police','atm','community_centre','bus_station','clinic','sport','shelter','toilets','hospital','post_office','bench','public_building','college','marketplace','kindergarten','fire_station','dentist','car_wash']
      - name: "Busyness"
        columns: ['Avg Clustering','Degree Centrality','Group Closeness Centrality', 'ntl_mean', 'ntl_median', 'ntl_min', 'ntl_max', 'ntl_std', 'ntl_sum', 'px_count', 'ntl_p10', 'ntl_p90', 'bright_frac', 'moderate_frac', 'dark_frac', 'ntl_gini', 'ntl_skew', 'ntl_kurtosis']
      - name: "Healthcare Facilities"
        columns: ['BHC_Count','Government_BedCount','Private_BedCount','Government_DialysisCenterCount','Private_DialysisCenterCount','Government_CancerCenterCount','Private_CancerCenterCount','Government_KTCenterCount','Private_KTCenterCount','Government_PsychCenterCount','Private_PsychCenterCount']
      - name: "Healthcare Providers"
        columns: ['PHAEST01','PHAEST02', 'PHCARD01','PHDIAB01','PHDIAB01','PHEMEMED01','PHENTS01','PHGENE01','PHGENE02','PHGENE03','PHGENE04','PHGENP01','PHINTM01','PHINTM02','PHOBGN01','PHORTS01','PHPEDI01','PHRANES01','PHREHAB01','PHRENDO01','PHRENDO01','PHRGAST01','PHRGAST02','PHRINFD01','PHRINFD02','PHRNEPH01','PHRNEUR01','PHRNEUR02','PHROCCU01','PHRONCO01','PHRONCO02','PHRONCO03','PHRPSYC02','PHRRHEU01','PHRUROL01']

  edges:
    # path: data/all_edges.csv
    path: data/all_edges.csv
    source_col: source_id
    target_col: target_id
    type_col: type

  counterfactuals:
    path: data/counterfactuals.csv
    id_col: location_id
    top_changes_col: top_changes

  lime:
    path: data/RAW_best_model.pkl
    datasource: data/final_merged_data_with_nighttimelights_08232025.csv
    feature_cols: ['location_id', 'shop','restaurant','school','bank','fast_food','place_of_worship','fuel','pharmacy','cafe','parking','townhall','bar','police','atm','community_centre','bus_station','clinic','sport','shelter','toilets','hospital','post_office','bench','public_building','college','marketplace','kindergarten','fire_station','dentist','car_wash','temp_min','temp_max','temp_avg','temp_median','temp_p25','temp_p75','temp_std','humidity_min','humidity_max','humidity_avg','humidity_median','humidity_p25','humidity_p75','humidity_std','precipitation_avg','precipitation_p75','precipitation_std','wind_min','wind_max','wind_avg','wind_median','wind_p25','wind_p75','wind_std','pressure_min','pressure_max','pressure_avg','pressure_median','pressure_p25','pressure_p75','pressure_std','clouds_avg','clouds_median','clouds_p25','clouds_p75','clouds_std','aqi_july_mean','pm2_5_july_mean','pm10_july_mean','no_july_mean','no2_july_mean','so2_july_mean','co_july_mean','o3_july_mean','nh3_july_mean','10','10.0.0.0.1','10.0.0.1','ai','anime','calculator','canva','chat','chat gpt','chatgpt','download','drawing','english tagalog','english to tagalog','face','facebook','fb','gmail','google','google translate','gpt','gpt chat','grow a garden','lotto result','map','messenger','movies','now','pag ibig','pinay','piso wifi','poster','reddit','result today','roblox','scandal','sias','sss','swertres','swertres result','swertres result today','tagalog english','tagalog to english','test','the','tiktok','time','time now','translate','translate english to tagalog','translate tagalog to english','translate to english','translate to tagalog','usd to php','videos','weather','weather tomorrow','wifi','wifi pause','you','youtube','Avg Clustering','Degree Centrality','Group Closeness Centrality','amenity_count','amenity_density_scaled','amenity_proximity_scaled','amenity_entropy_scaled','amenity_equity_scaled','ntl_mean','ntl_median','ntl_min','ntl_max','ntl_std','ntl_sum','px_count','ntl_p10','ntl_p90','bright_frac','moderate_frac','dark_frac','ntl_gini','ntl_skew','ntl_kurtosis']
    label_names: ['Tier 1', 'Tier 2', 'Tier 3', 'Tier 4']